image: registry.gitlab.com/codinghighway/codinghighway:latest

services:
- mysql:5.7

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

stages:
- test
- deploy_dev
- deploy_staging
- deploy

unit_test:
  stage: test
  script:
  - cp .env.example .env
  - cp .env.example .env.testing
  - composer install
  - php artisan db:create
  - php artisan key:generate
  - php artisan key:generate --env=testing
  - php artisan migrate
  - php artisan migrate --env=testing
  - vendor/bin/phpunit

deploy_dev:
  stage: deploy_dev
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    - ~/.composer/vendor/bin/envoy run deploy --branch=dev
  environment:
    name: development
    url: http://dev.codinghighway.nl
  only:
    - dev

deploy_staging:
  stage: deploy_staging
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    - ~/.composer/vendor/bin/envoy run deploy --branch=staging
  environment:
    name: staging
    url: http://staging.codinghighway.nl
  only:
    - staging

deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    - ~/.composer/vendor/bin/envoy run deploy --branch=master
  environment:
    name: production
    url: http://codinghighway.nl
  only:
    - master