<?php

use Illuminate\Database\Seeder;

class OrganisationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('organisations')->delete();
        
        \DB::table('organisations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Paucek Inc',
                'street' => 'Murazik Burg',
                'housenumber' => '402',
                'zipcode' => '52112-1139',
                'city' => 'Borerview',
                'email' => 'xdach@jakubowski.com',
                'paper_invoice' => 0,
                'color' => '#7f1bd5',
                'fontcolor' => '#8eb47e',
                'image' => NULL,
                'link' => 'http://www.labadie.info/qui-inventore-architecto-eaque-sapiente.html',
                'active' => 0,
                'requester' => NULL,
                'phone' => NULL,
                'created_at' => '2018-11-29 09:01:44',
                'updated_at' => '2018-11-29 09:01:44',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Anderson PLC',
                'street' => 'Norene Stravenue',
                'housenumber' => '26059',
                'zipcode' => '31825-7420',
                'city' => 'West Ronaldotown',
                'email' => 'bernhard61@abshire.info',
                'paper_invoice' => 1,
                'color' => '#e3f5d8',
                'fontcolor' => '#f18750',
                'image' => NULL,
                'link' => 'http://www.schinner.net/asperiores-hic-officia-deleniti-fugit-necessitatibus-aspernatur-ratione',
                'active' => 0,
                'requester' => NULL,
                'phone' => NULL,
                'created_at' => '2018-11-29 09:01:44',
                'updated_at' => '2018-11-29 09:01:44',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Hamill-Legros',
                'street' => 'Champlin Springs',
                'housenumber' => '47082',
                'zipcode' => '28778-7508',
                'city' => 'East Priscilla',
                'email' => 'oterry@kerluke.org',
                'paper_invoice' => 0,
                'color' => '#9ae9f6',
                'fontcolor' => '#2d5bcf',
                'image' => NULL,
                'link' => 'http://www.littel.com/',
                'active' => 0,
                'requester' => NULL,
                'phone' => NULL,
                'created_at' => '2018-11-29 09:01:44',
                'updated_at' => '2018-11-29 09:01:44',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Beier, Bednar and Padberg',
                'street' => 'Schoen Courts',
                'housenumber' => '99585',
                'zipcode' => '92153-4792',
                'city' => 'Ardithton',
                'email' => 'grimes.dixie@roberts.com',
                'paper_invoice' => 1,
                'color' => '#47e11d',
                'fontcolor' => '#d564a3',
                'image' => NULL,
                'link' => 'http://www.yost.net/nihil-nihil-ut-velit-itaque',
                'active' => 0,
                'requester' => NULL,
                'phone' => NULL,
                'created_at' => '2018-11-29 09:01:44',
                'updated_at' => '2018-11-29 09:01:44',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Glover PLC',
                'street' => 'Easton Knoll',
                'housenumber' => '763',
                'zipcode' => '72352',
                'city' => 'North Bradly',
                'email' => 'gilbert.wisoky@mosciski.biz',
                'paper_invoice' => 1,
                'color' => '#9b9b73',
                'fontcolor' => '#bd205c',
                'image' => NULL,
                'link' => 'http://www.runte.com/dolores-porro-quam-velit-et-vel-doloribus-quia-quia',
                'active' => 0,
                'requester' => NULL,
                'phone' => NULL,
                'created_at' => '2018-11-29 09:01:44',
                'updated_at' => '2018-11-29 09:01:44',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Gerlach-Reinger',
                'street' => 'Beer Well',
                'housenumber' => '4922',
                'zipcode' => '78676-8070',
                'city' => 'Huelsborough',
                'email' => 'madaline.casper@swaniawski.com',
                'paper_invoice' => 1,
                'color' => '#3a54ed',
                'fontcolor' => '#fb74f4',
                'image' => NULL,
                'link' => 'http://bednar.com/',
                'active' => 0,
                'requester' => NULL,
                'phone' => NULL,
                'created_at' => '2018-11-29 09:01:44',
                'updated_at' => '2018-11-29 09:01:44',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Grant, Ankunding and Schneider',
                'street' => 'Barton Ports',
                'housenumber' => '5374',
                'zipcode' => '93674',
                'city' => 'New Aylaburgh',
                'email' => 'waino69@kling.com',
                'paper_invoice' => 0,
                'color' => '#096932',
                'fontcolor' => '#17375a',
                'image' => NULL,
                'link' => 'http://nicolas.biz/qui-id-rem-pariatur-aperiam-in-est.html',
                'active' => 0,
                'requester' => NULL,
                'phone' => NULL,
                'created_at' => '2018-11-29 09:01:44',
                'updated_at' => '2018-11-29 09:01:44',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Blanda-Watsica',
                'street' => 'Blick Fort',
                'housenumber' => '6428',
                'zipcode' => '31426-8485',
                'city' => 'Lake Maximillianborough',
                'email' => 'maya26@wuckert.com',
                'paper_invoice' => 1,
                'color' => '#623f64',
                'fontcolor' => '#a50a4f',
                'image' => NULL,
                'link' => 'http://www.bogisich.net/reprehenderit-ducimus-velit-suscipit-unde-voluptatem-aut.html',
                'active' => 0,
                'requester' => NULL,
                'phone' => NULL,
                'created_at' => '2018-11-29 09:01:44',
                'updated_at' => '2018-11-29 09:01:44',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Murazik Inc',
                'street' => 'Miller Parkway',
                'housenumber' => '65814',
                'zipcode' => '93654',
                'city' => 'Kubberg',
                'email' => 'marta40@zemlak.net',
                'paper_invoice' => 1,
                'color' => '#9f253d',
                'fontcolor' => '#b2d5d4',
                'image' => NULL,
                'link' => 'http://www.jacobi.org/qui-ab-porro-sed-sit.html',
                'active' => 0,
                'requester' => NULL,
                'phone' => NULL,
                'created_at' => '2018-11-29 09:01:44',
                'updated_at' => '2018-11-29 09:01:44',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Treutel, Torphy and Johns',
                'street' => 'Valentina Station',
                'housenumber' => '708',
                'zipcode' => '54143',
                'city' => 'Hoppeton',
                'email' => 'ariane.wiegand@homenick.com',
                'paper_invoice' => 0,
                'color' => '#71bba3',
                'fontcolor' => '#ed114b',
                'image' => NULL,
                'link' => 'http://www.ward.com/doloribus-voluptas-repellendus-voluptatem-quod-eos',
                'active' => 0,
                'requester' => NULL,
                'phone' => NULL,
                'created_at' => '2018-11-29 09:01:44',
                'updated_at' => '2018-11-29 09:01:44',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'ROC van Flevoland',
                'street' => 'Straat van Florida',
                'housenumber' => '1',
                'zipcode' => '1334PA',
                'city' => 'Almere',
                'email' => 'informatiecentrum@rocvf.nl',
                'paper_invoice' => 0,
                'color' => '#ee7326',
                'fontcolor' => '#ee7326',
                'image' => 1,
                'link' => 'https://www.rocvanflevoland.nl',
                'active' => 1,
                'requester' => 1,
                'phone' => '0365495900',
                'created_at' => '2018-11-29 09:31:15',
                'updated_at' => '2018-11-29 09:32:53',
            ),
        ));
        
        
    }
}